name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2023.07=py39_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py39hecd8cb5_1
  - abseil-cpp=20211102.0=he9d5cce_0
  - aiobotocore=2.5.0=py39hecd8cb5_0
  - aiohttp=3.8.3=py39h6c40b1e_0
  - aioitertools=0.7.1=pyhd3eb1b0_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py39_1
  - anaconda-client=1.12.0=py39hecd8cb5_0
  - anaconda-navigator=2.3.1=py39hecd8cb5_0
  - anyio=3.5.0=py39hecd8cb5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - applaunchservices=0.3.0=py39hecd8cb5_0
  - appnope=0.1.2=py39hecd8cb5_1001
  - appscript=1.1.2=py39h9ed2024_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39hca72f7f_0
  - arrow=1.2.3=py39hecd8cb5_1
  - arrow-cpp=11.0.0=py39h7f74497_0
  - astroid=2.14.2=py39hecd8cb5_0
  - astropy=5.1=py39h67323c0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py39hecd8cb5_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py39hecd8cb5_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - aws-c-common=0.4.57=hb1e8313_1
  - aws-c-event-stream=0.1.6=h23ab428_5
  - aws-checksums=0.1.9=hb1e8313_0
  - aws-sdk-cpp=1.8.185=he271ece_0
  - babel=2.11.0=py39hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py39hca72f7f_1
  - beautifulsoup4=4.12.2=py39hecd8cb5_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=23.3.0=py39hecd8cb5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=hcec6c5f_0
  - bokeh=3.1.1=py39h20db666_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - boost-cpp=1.73.0=hca72f7f_12
  - botocore=1.29.76=py39hecd8cb5_0
  - bottleneck=1.3.5=py39h67323c0_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - brotlipy=0.7.0=py39h9ed2024_1003
  - brunsli=0.1=h23ab428_0
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.19.0=h6c40b1e_0
  - c-blosc2=2.8.0=hcec6c5f_0
  - ca-certificates=2023.5.7=h8857fd0_0
  - cctools=949.0.1=h9abeeb2_25
  - cctools_osx-64=949.0.1=hc7db93f_25
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h6c40b1e_3
  - cfitsio=3.470=hbd21bf8_7
  - chardet=4.0.0=py39hecd8cb5_1003
  - charls=2.2.0=h23ab428_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39hecd8cb5_0
  - cloudpickle=2.2.1=py39hecd8cb5_0
  - clyent=1.2.2=py39hecd8cb5_1
  - colorama=0.4.6=py39hecd8cb5_0
  - colorcet=3.0.1=py39hecd8cb5_0
  - comm=0.1.2=py39hecd8cb5_0
  - conda=23.5.2=py39h6e9494a_0
  - conda-build=3.22.0=py39hecd8cb5_0
  - conda-content-trust=0.1.3=py39hecd8cb5_0
  - conda-env=2.6.0=1
  - conda-package-handling=2.1.0=py39hecd8cb5_0
  - conda-package-streaming=0.8.0=py39hecd8cb5_0
  - conda-repo-cli=1.0.41=py39hecd8cb5_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - constantly=15.1.0=pyh2b92418_0
  - contourpy=1.0.5=py39haf03e11_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.1=py39hf6deb26_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - curl=8.1.1=h6c40b1e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py39hca72f7f_0
  - dask=2023.6.0=py39hecd8cb5_0
  - dask-core=2023.6.0=py39hecd8cb5_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datashader=0.15.1=py39hecd8cb5_0
  - datashape=0.5.4=py39hecd8cb5_1
  - debugpy=1.5.1=py39he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py39hecd8cb5_0
  - distributed=2023.6.0=py39hecd8cb5_0
  - docstring-to-markdown=0.11=py39hecd8cb5_0
  - entrypoints=0.4=py39hecd8cb5_0
  - et_xmlfile=1.1.0=py39hecd8cb5_0
  - exceptiongroup=1.0.4=py39hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.9.0=py39hecd8cb5_0
  - flake8=6.0.0=py39hecd8cb5_0
  - flask=1.1.2=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - frozenlist=1.3.3=py39h6c40b1e_0
  - fsspec=2023.4.0=py39hecd8cb5_0
  - future=0.18.3=py39hecd8cb5_0
  - gensim=4.3.0=py39hcec6c5f_0
  - gettext=0.21.0=he85b6c0_1
  - gflags=2.2.2=h0a44026_0
  - gh=2.32.0=h990441c_0
  - giflib=5.2.1=h6c40b1e_3
  - glib=2.69.1=hfff2838_2
  - glob2=0.7=pyhd3eb1b0_0
  - glog=0.5.0=h23ab428_0
  - gmp=6.2.1=he9d5cce_3
  - gmpy2=2.1.2=py39hd5de756_0
  - greenlet=2.0.1=py39hcec6c5f_0
  - grpc-cpp=1.46.1=h64d96ca_1
  - gst-plugins-base=1.14.1=hcec6c5f_1
  - gstreamer=1.14.1=h6c40b1e_1
  - h5py=3.7.0=py39h4a1dd59_0
  - hdf5=1.10.6=h10fe05b_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.16.2=py39hecd8cb5_0
  - huggingface_hub=0.15.1=py39hecd8cb5_0
  - hvplot=0.8.4=py39hecd8cb5_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=58.2=h0a44026_3
  - idna=3.4=py39hecd8cb5_0
  - imagecodecs=2021.8.26=py39h8a96914_2
  - imageio=2.31.1=py39hecd8cb5_0
  - imagesize=1.4.1=py39hecd8cb5_0
  - imbalanced-learn=0.10.1=py39hecd8cb5_1
  - importlib-metadata=6.0.0=py39hecd8cb5_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py39hecd8cb5_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.8=py39hecd8cb5_0
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.19.2=py39h01d92e1_0
  - ipython=8.12.0=py39hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py39hecd8cb5_0
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.18.1=py39hecd8cb5_1
  - jellyfish=0.9.0=py39hca72f7f_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.2.0=py39hecd8cb5_0
  - jpeg=9e=h6c40b1e_1
  - jq=1.6=h9ed2024_1000
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.17.3=py39hecd8cb5_0
  - jupyter=1.0.0=py39hecd8cb5_8
  - jupyter_client=8.1.0=py39hecd8cb5_0
  - jupyter_console=6.6.3=py39hecd8cb5_0
  - jupyter_core=5.3.0=py39hecd8cb5_0
  - jupyter_server=1.23.4=py39hecd8cb5_0
  - jupyterlab=3.5.3=py39hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=3.0.5=py39hecd8cb5_0
  - jxrlib=1.1=haf1e3a3_2
  - keyring=23.13.1=py39hecd8cb5_0
  - kiwisolver=1.4.4=py39hcec6c5f_0
  - krb5=1.19.4=hdba6334_0
  - lazy-object-proxy=1.6.0=py39h9ed2024_0
  - lcms2=2.12=hf1fd2bf_0
  - ld64=530=h20443b4_25
  - ld64_osx-64=530=h70f3046_25
  - ldid=2.1.5=hc58f1be_3
  - lerc=3.0=he9d5cce_0
  - libaec=1.0.4=hb1e8313_1
  - libarchive=3.6.2=had00e1f_1
  - libboost=1.73.0=h3fa6bed_12
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libclang=14.0.6=default_hd95374b_1
  - libclang13=14.0.6=default_habbcc1a_1
  - libcurl=8.1.1=ha585b31_0
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_0
  - libedit=3.1.20221030=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h0a4fc7d_0
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.16=hca72f7f_2
  - liblief=0.12.3=hcec6c5f_0
  - libllvm14=14.0.6=h91fad77_3
  - libnghttp2=1.52.0=h1c88b7d_1
  - libopenblas=0.3.21=h54e7dc3_0
  - libpng=1.6.39=h6c40b1e_0
  - libpq=12.9=h1c9f633_3
  - libprotobuf=3.20.3=hfff2838_0
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libssh2=1.10.0=hdb2fb19_2
  - libthrift=0.15.0=h48f73ad_2
  - libtiff=4.5.0=hcec6c5f_2
  - libuv=1.44.2=h6c40b1e_0
  - libwebp=1.2.4=hf6ce154_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxml2=2.10.3=h930c0e2_0
  - libxslt=1.1.37=h6d1eb0e_0
  - libzopfli=1.0.3=hb1e8313_0
  - linkify-it-py=2.0.0=py39hecd8cb5_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - llvmlite=0.40.0=py39hfff2838_0
  - locket=1.0.0=py39hecd8cb5_0
  - lxml=4.9.2=py39h6c40b1e_0
  - lz4=4.3.2=py39h6c40b1e_0
  - lz4-c=1.9.4=hcec6c5f_0
  - lzo=2.10=haf1e3a3_2
  - markdown=3.4.1=py39hecd8cb5_0
  - markdown-it-py=2.2.0=py39hecd8cb5_1
  - markupsafe=2.0.1=py39h9ed2024_0
  - matplotlib=3.7.1=py39hecd8cb5_1
  - matplotlib-base=3.7.1=py39hda11e5a_1
  - matplotlib-inline=0.1.6=py39hecd8cb5_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py39h9ed2024_1000
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpmath=1.2.1=py39hecd8cb5_0
  - msgpack-python=1.0.3=py39haf03e11_0
  - multidict=6.0.2=py39hca72f7f_0
  - multipledispatch=0.6.0=py39hecd8cb5_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39hecd8cb5_1
  - navigator-updater=0.3.0=py39hecd8cb5_0
  - nbclassic=0.5.5=py39hecd8cb5_0
  - nbclient=0.5.13=py39hecd8cb5_0
  - nbconvert=6.4.4=py39hecd8cb5_0
  - nbformat=5.7.0=py39hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py39hecd8cb5_0
  - networkx=2.8.4=py39hecd8cb5_1
  - ninja=1.10.2=hecd8cb5_5
  - ninja-base=1.10.2=haf03e11_5
  - nltk=3.8.1=py39hecd8cb5_0
  - notebook=6.5.4=py39hecd8cb5_0
  - notebook-shim=0.2.2=py39hecd8cb5_0
  - nspr=4.35=hcec6c5f_0
  - nss=3.89.1=hcec6c5f_0
  - numba=0.57.0=py39h3ea8b11_0
  - numexpr=2.8.4=py39h57a7bef_1
  - numpy=1.24.3=py39h57a7bef_0
  - numpy-base=1.24.3=py39hc93c6d9_0
  - numpydoc=1.5.0=py39hecd8cb5_0
  - oniguruma=6.9.7.1=h9ed2024_0
  - openjpeg=2.4.0=h66ea3da_0
  - openpyxl=3.0.10=py39hca72f7f_0
  - openssl=1.1.1u=h8a1eda9_0
  - orc=1.7.4=h995b336_1
  - packaging=23.0=py39hecd8cb5_0
  - pandas=1.4.4=py39he9d5cce_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=1.1.0=py39hecd8cb5_0
  - param=1.13.0=py39hecd8cb5_0
  - parsel=1.6.0=py39hecd8cb5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patch=2.7.6=h1de35cc_1001
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pathspec=0.10.3=py39hecd8cb5_0
  - patsy=0.5.3=py39hecd8cb5_0
  - pcre=8.45=h23ab428_0
  - pep8=1.7.1=py39hecd8cb5_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py39hcec6c5f_0
  - pip=23.1.2=py39hecd8cb5_0
  - pkginfo=1.9.6=py39hecd8cb5_0
  - platformdirs=2.5.2=py39hecd8cb5_0
  - plotly=5.9.0=py39hecd8cb5_0
  - pluggy=1.0.0=py39hecd8cb5_1
  - ply=3.11=py39hecd8cb5_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py39hecd8cb5_0
  - prompt-toolkit=3.0.36=py39hecd8cb5_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protego=0.1.16=py_0
  - psutil=5.9.0=py39hca72f7f_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=8.0.0=pyhd3eb1b0_1
  - py-lief=0.12.3=py39hcec6c5f_0
  - pyarrow=11.0.0=py39h7122ad0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.10.0=py39hecd8cb5_0
  - pycosat=0.6.4=py39hca72f7f_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py39hecd8cb5_0
  - pycurl=7.45.2=py39hdb2fb19_0
  - pydispatcher=2.0.5=py39hecd8cb5_2
  - pydocstyle=6.3.0=py39hecd8cb5_0
  - pyerfa=2.0.0=py39h9ed2024_0
  - pyflakes=3.0.1=py39hecd8cb5_0
  - pygments=2.15.1=py39hecd8cb5_1
  - pyjwt=2.4.0=py39hecd8cb5_0
  - pylint=2.16.2=py39hecd8cb5_0
  - pylint-venv=2.3.0=py39hecd8cb5_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyobjc-core=9.0=py39h9205ec4_1
  - pyobjc-framework-cocoa=9.0=py39h9205ec4_0
  - pyobjc-framework-coreservices=9.0=py39h46256e1_0
  - pyobjc-framework-fsevents=9.0=py39hecd8cb5_0
  - pyodbc=4.0.34=py39he9d5cce_0
  - pyopenssl=23.0.0=py39hecd8cb5_0
  - pyparsing=3.0.9=py39hecd8cb5_0
  - pyqt=5.15.7=py39he9d5cce_0
  - pyqt5-sip=12.11.0=py39he9d5cce_0
  - pyqtwebengine=5.15.7=py39he9d5cce_0
  - pyrsistent=0.18.0=py39hca72f7f_0
  - pysocks=1.7.1=py39hecd8cb5_0
  - pytables=3.8.0=py39hbdc8ef1_2
  - pytest=7.3.1=py39hecd8cb5_0
  - python=3.9.17=h218abb5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39hecd8cb5_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lmdb=1.4.1=py39hcec6c5f_0
  - python-lsp-black=1.2.1=py39hecd8cb5_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.2=py39hecd8cb5_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.1=py39hcec6c5f_0
  - python.app=3=py39hca72f7f_0
  - python_abi=3.9=2_cp39
  - pytoolconfig=1.2.5=py39hecd8cb5_1
  - pytorch=1.13.1=cpu_py39h9e40b02_0
  - pytz=2022.7=py39hecd8cb5_0
  - pyviz_comms=2.3.0=py39hecd8cb5_0
  - pywavelets=1.4.1=py39h6c40b1e_0
  - pyyaml=6.0=py39h6c40b1e_1
  - pyzmq=25.1.0=py39hcec6c5f_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=py39hecd8cb5_0
  - qt-main=5.15.2=h51e0635_8
  - qt-webengine=5.15.9=h90a370e_4
  - qtawesome=1.2.2=py39hecd8cb5_0
  - qtconsole=5.4.2=py39hecd8cb5_0
  - qtpy=2.2.0=py39hecd8cb5_0
  - qtwebkit=5.212=hbfab81c_5
  - queuelib=1.5.0=py39hecd8cb5_0
  - re2=2022.04.01=he9d5cce_0
  - readline=8.2=hca72f7f_0
  - regex=2022.7.9=py39hca72f7f_0
  - requests=2.29.0=py39hecd8cb5_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - requests-toolbelt=0.9.1=pyhd3eb1b0_0
  - ripgrep=13.0.0=h46731b9_1
  - rope=1.7.0=py39hecd8cb5_0
  - rtree=1.0.1=py39hecd8cb5_0
  - ruamel.yaml=0.17.32=py39hdc70f33_0
  - ruamel.yaml.clib=0.2.7=py39ha30fb19_1
  - ruamel_yaml=0.15.100=py39h9ed2024_0
  - s3fs=2023.4.0=py39hecd8cb5_0
  - scikit-image=0.19.3=py39hcec6c5f_1
  - scikit-learn=1.2.2=py39hcec6c5f_1
  - scipy=1.10.1=py39h9034365_1
  - scrapy=2.8.0=py39hecd8cb5_0
  - seaborn=0.12.2=py39hecd8cb5_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=67.8.0=py39hecd8cb5_0
  - sip=6.6.2=py39he9d5cce_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py39hecd8cb5_0
  - snappy=1.1.9=he9d5cce_0
  - sniffio=1.2.0=py39hecd8cb5_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.4=py39hecd8cb5_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.4.3=py39hecd8cb5_1
  - spyder-kernels=2.4.3=py39hecd8cb5_0
  - sqlalchemy=1.4.39=py39hca72f7f_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py39hacda100_1
  - sympy=1.11.1=py39hecd8cb5_0
  - tabulate=0.8.10=py39hecd8cb5_0
  - tapi=1000.10.8=ha1b3eb9_0
  - tbb=2021.8.0=ha357a0b_0
  - tbb4py=2021.8.0=py39ha357a0b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.2=py39hecd8cb5_0
  - terminado=0.17.1=py39hecd8cb5_0
  - testpath=0.6.0=py39hecd8cb5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=py39hecd8cb5_0
  - tk=8.6.12=h5d9f67b_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - tokenizers=0.13.2=py39h5240035_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39hecd8cb5_0
  - tomlkit=0.11.1=py39hecd8cb5_0
  - toolz=0.12.0=py39hecd8cb5_0
  - tornado=6.2=py39hca72f7f_0
  - tqdm=4.65.0=py39h01d92e1_0
  - traitlets=5.7.1=py39hecd8cb5_0
  - transformers=4.24.0=py39hecd8cb5_0
  - twisted=22.10.0=py39h6c40b1e_0
  - typing-extensions=4.6.3=py39hecd8cb5_0
  - typing_extensions=4.6.3=py39hecd8cb5_0
  - tzdata=2023c=h04d1e81_0
  - uc-micro-py=1.0.1=py39hecd8cb5_0
  - ujson=5.4.0=py39he9d5cce_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.11=hb456775_0
  - urllib3=1.26.16=py39hecd8cb5_0
  - utf8proc=2.6.1=h9ed2024_0
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py39h999c104_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hecd8cb5_1
  - websocket-client=0.58.0=py39hecd8cb5_4
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - whatthepatch=1.0.2=py39hecd8cb5_0
  - wheel=0.38.4=py39hecd8cb5_0
  - widgetsnbextension=4.0.5=py39hecd8cb5_0
  - wrapt=1.14.1=py39hca72f7f_0
  - wurlitzer=3.0.2=py39hecd8cb5_0
  - xarray=2023.6.0=py39hecd8cb5_0
  - xlwings=0.29.1=py39hecd8cb5_0
  - xyzservices=2022.9.0=py39hecd8cb5_1
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - yarl=1.8.1=py39hca72f7f_0
  - zeromq=4.3.4=h23ab428_0
  - zfp=0.5.5=he9d5cce_6
  - zict=2.2.0=py39hecd8cb5_0
  - zipp=3.11.0=py39hecd8cb5_0
  - zlib=1.2.13=h4dc903c_0
  - zlib-ng=2.0.7=h6c40b1e_0
  - zope=1.0=py39hecd8cb5_1
  - zope.interface=5.4.0=py39h9ed2024_0
  - zstandard=0.19.0=py39h6c40b1e_0
  - zstd=1.5.5=hc035e20_0
#   - pip:
#       - docutils==0.20.1
#       - jinja2==3.1.2
#       - libopencv==0.0.1
#       - mdit-py-plugins==0.3.5
#       - mdurl==0.1.2
#       - myst-parser==1.0.0
#       - opencv-contrib-python==4.7.0.72
#       - pyfdstools==0.0.8
#       - renku-sphinx-theme==0.2.3
#       - sphinx==7.1.0
#       - sphinx-rtd-theme==1.1.1
#       - sphinxcontrib-jquery==4.1
