# MaCFP workflow

name: Experimental_Data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [ master ]
    paths:
      - .github/workflows/Experimental_Data.yml
      - Utilities/macfp.py
      - Buoyant_Plumes/Sandia_Helium_Plume/Experimental_Data/**
      - Extinction/FM_Burner/Experimental_Data/**
      - Gaseous_Pool_Fires/McCaffrey_Flames/Experimental_Data/**
      - Gaseous_Pool_Fires/Sandia_Flames/Experimental_Data/**
      - Liquid_Pool_Fires/Waterloo_Methanol/Experimental_Data/**
      - Liquid_Pool_Fires/NIST_Pool_Fires/Experimental_Data/**
      - Wall_Fires/FM_Vertical_Wall_Flames/Experimental_Data/**
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/Experimental_Data.yml
      - Utilities/macfp.py
      - Buoyant_Plumes/Sandia_Helium_Plume/Experimental_Data/**
      - Extinction/FM_Burner/Experimental_Data/**
      - Gaseous_Pool_Fires/McCaffrey_Flames/Experimental_Data/**
      - Gaseous_Pool_Fires/Sandia_Flames/Experimental_Data/**
      - Liquid_Pool_Fires/Waterloo_Methanol/Experimental_Data/**
      - Liquid_Pool_Fires/NIST_Pool_Fires/Experimental_Data/**
      - Wall_Fires/FM_Vertical_Wall_Flames/Experimental_Data/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r .github/requirements.txt

      # Generate new plots
      - name: Generate experimental data plots
        run: |
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/Buoyant_Plumes/Sandia_Helium_Plume/Scripts  && python Sandia_Helium_Plume_plot_exp.py
          cd $GITHUB_WORKSPACE/Extinction/FM_Burner/Scripts                && python FM_Burner_plot_exp.py
          cd $GITHUB_WORKSPACE/Liquid_Pool_Fires/NIST_Pool_Fires/Scripts   && python NIST_Pool_Fires_plot_exp.py
          cd $GITHUB_WORKSPACE/Liquid_Pool_Fires/Waterloo_Methanol/Scripts && python Waterloo_Methanol_plot_exp.py